Running Java benchmark MGopt, class D, on 4 servers (np=4), usnic,self

Servers:
mpi005
mpi013
mpi028
mpi032

mpirun --mca btl usnic,self --bind-to core --map-by node -np 4 java NPB_MPJ.MGopt class=D

Start: Mon Feb 17 11:58:22 PST 2014
===============================================================================
Exception in thread "main" java.lang.NegativeArraySizeException
Exception in thread "main" java.lang.NegativeArraySizeException
	at NPB_MPJ.MGopt.runBenchmark(MGopt.java:198)
	at NPB_MPJ.MGopt.main(MGopt.java:113)
	at NPB_MPJ.MGopt.runBenchmark(MGopt.java:198)
Exception in thread "main" java.lang.NegativeArraySizeException
	at NPB_MPJ.MGopt.main(MGopt.java:113)	at NPB_MPJ.MGopt.runBenchmark(MGopt.java:198)

	at NPB_MPJ.MGopt.main(MGopt.java:113)
Exception in thread "main" java.lang.NegativeArraySizeException
	at NPB_MPJ.MGopt.runBenchmark(MGopt.java:198)
	at NPB_MPJ.MGopt.main(MGopt.java:113)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[17558,1],2]
  Exit code:    1
--------------------------------------------------------------------------
===============================================================================
End: Mon Feb 17 11:58:27 PST 2014
